import process from 'node:process';globalThis._importMeta_={url:import.meta.url,env:process.env};export { d as closePrerenderer, l as localFetch } from './chunks/runtime.mjs';
import 'file://C:/Users/Alpha/Videos/robert/vue%20js/updated/mindboost-webapp-rapp-noisepatch_one_band_merge_branch/mindboost-webapp%20-%20Copy/node_modules/h3/dist/index.mjs';
import 'file://C:/Users/Alpha/Videos/robert/vue%20js/updated/mindboost-webapp-rapp-noisepatch_one_band_merge_branch/mindboost-webapp%20-%20Copy/node_modules/ofetch/dist/node.mjs';
import 'file://C:/Users/Alpha/Videos/robert/vue%20js/updated/mindboost-webapp-rapp-noisepatch_one_band_merge_branch/mindboost-webapp%20-%20Copy/node_modules/destr/dist/index.mjs';
import 'file://C:/Users/Alpha/Videos/robert/vue%20js/updated/mindboost-webapp-rapp-noisepatch_one_band_merge_branch/mindboost-webapp%20-%20Copy/node_modules/unenv/runtime/fetch/index.mjs';
import 'file://C:/Users/Alpha/Videos/robert/vue%20js/updated/mindboost-webapp-rapp-noisepatch_one_band_merge_branch/mindboost-webapp%20-%20Copy/node_modules/hookable/dist/index.mjs';
import 'file://C:/Users/Alpha/Videos/robert/vue%20js/updated/mindboost-webapp-rapp-noisepatch_one_band_merge_branch/mindboost-webapp%20-%20Copy/node_modules/klona/dist/index.mjs';
import 'file://C:/Users/Alpha/Videos/robert/vue%20js/updated/mindboost-webapp-rapp-noisepatch_one_band_merge_branch/mindboost-webapp%20-%20Copy/node_modules/scule/dist/index.mjs';
import 'file://C:/Users/Alpha/Videos/robert/vue%20js/updated/mindboost-webapp-rapp-noisepatch_one_band_merge_branch/mindboost-webapp%20-%20Copy/node_modules/defu/dist/defu.mjs';
import 'file://C:/Users/Alpha/Videos/robert/vue%20js/updated/mindboost-webapp-rapp-noisepatch_one_band_merge_branch/mindboost-webapp%20-%20Copy/node_modules/ohash/dist/index.mjs';
import 'file://C:/Users/Alpha/Videos/robert/vue%20js/updated/mindboost-webapp-rapp-noisepatch_one_band_merge_branch/mindboost-webapp%20-%20Copy/node_modules/unstorage/dist/index.mjs';
import 'file://C:/Users/Alpha/Videos/robert/vue%20js/updated/mindboost-webapp-rapp-noisepatch_one_band_merge_branch/mindboost-webapp%20-%20Copy/node_modules/unstorage/drivers/fs.mjs';
import 'file:///C:/Users/Alpha/Videos/robert/vue%20js/updated/mindboost-webapp-rapp-noisepatch_one_band_merge_branch/mindboost-webapp%20-%20Copy/node_modules/nuxt/dist/core/runtime/nitro/cache-driver.js';
import 'file://C:/Users/Alpha/Videos/robert/vue%20js/updated/mindboost-webapp-rapp-noisepatch_one_band_merge_branch/mindboost-webapp%20-%20Copy/node_modules/unstorage/drivers/fs-lite.mjs';
import 'file://C:/Users/Alpha/Videos/robert/vue%20js/updated/mindboost-webapp-rapp-noisepatch_one_band_merge_branch/mindboost-webapp%20-%20Copy/node_modules/radix3/dist/index.mjs';
import 'node:fs';
import 'node:url';
import 'file://C:/Users/Alpha/Videos/robert/vue%20js/updated/mindboost-webapp-rapp-noisepatch_one_band_merge_branch/mindboost-webapp%20-%20Copy/node_modules/pathe/dist/index.mjs';
//# sourceMappingURL=index.mjs.map
